// ============================================================================
// Recursion — Exercises
// ============================================================================
// Config: ES2022, strict mode, ESNext modules. Run with `npx tsx exercises.ts`
//
// 15 exercises total:
//   - 5 predict (trace through mentally, then verify)
//   - 3 fix (buggy implementations to debug)
//   - 7 implement (write from scratch)
//
// Tests are commented out. Uncomment to verify your solutions.
// ============================================================================

// ---------------------------------------------------------------------------
// PREDICT EXERCISES (5)
// ---------------------------------------------------------------------------

// PREDICT 1: Factorial Call Stack
// Trace the call stack for factorial(5). How many stack frames exist at the
// deepest point? What value does each frame return?
//
// Your prediction:
//   Deepest stack depth: ???
//   factorial(1) returns: ???
//   factorial(2) returns: ???
//   factorial(3) returns: ???
//   factorial(4) returns: ???
//   factorial(5) returns: ???
//
// function predictFactorial(): void {
//   function factorial(n: number): number {
//     console.log(`  entering factorial(${n})`);
//     if (n <= 1) { console.log(`  base case: return 1`); return 1; }
//     const result = n * factorial(n - 1);
//     console.log(`  factorial(${n}) = ${result}`);
//     return result;
//   }
//   console.log("Result:", factorial(5));
// }
// predictFactorial();

// PREDICT 2: Fibonacci Call Count
// How many times is fib() called (total, including the initial call) for fib(6)?
//
// fib(6) calls fib(5) and fib(4)
// fib(5) calls fib(4) and fib(3)
// ... and so on
//
// Your prediction:
//   Total function calls: ???
//   Result of fib(6): ???
//
// function predictFibCalls(): void {
//   let calls = 0;
//   function fib(n: number): number {
//     calls++;
//     if (n <= 0) return 0;
//     if (n === 1) return 1;
//     return fib(n - 1) + fib(n - 2);
//   }
//   console.log("fib(6):", fib(6), "calls:", calls);
// }
// predictFibCalls();

// PREDICT 3: Recursive Sum Order
// What order are the console.logs printed?
//
// function sum(arr: number[]): number {
//   if (arr.length === 0) return 0;
//   console.log("Processing:", arr[0]);
//   return arr[0] + sum(arr.slice(1));
// }
// sum([10, 20, 30]);
//
// Your prediction (order of "Processing" messages):
//   1. Processing: ???
//   2. Processing: ???
//   3. Processing: ???
//   Return value: ???

// PREDICT 4: Power Function
// Trace power(2, 5) using this implementation. How many multiplications?
//
// function power(base: number, exp: number): number {
//   if (exp === 0) return 1;
//   if (exp % 2 === 0) {
//     const half = power(base, exp / 2);
//     return half * half;
//   }
//   return base * power(base, exp - 1);
// }
//
// Your prediction:
//   power(2, 5) → 2 * power(2, 4)
//   power(2, 4) → half = power(2, 2); half * half
//   power(2, 2) → half = power(2, 1); half * half
//   power(2, 1) → 2 * power(2, 0)
//   power(2, 0) → 1
//
//   Total multiplications: ???
//   Result: ???

// PREDICT 5: Subsets Generation
// What is the output of generateSubsets([1, 2, 3])?
// List all subsets in the order they would be generated by this algorithm:
//
// function generateSubsets(nums: number[]): number[][] {
//   const result: number[][] = [];
//   function backtrack(start: number, current: number[]): void {
//     result.push([...current]);
//     for (let i = start; i < nums.length; i++) {
//       current.push(nums[i]);
//       backtrack(i + 1, current);
//       current.pop();
//     }
//   }
//   backtrack(0, []);
//   return result;
// }
//
// Your prediction (list all 8 subsets in order):
//   1. ???
//   2. ???
//   ... etc.

// ---------------------------------------------------------------------------
// FIX EXERCISES (3)
// ---------------------------------------------------------------------------

// FIX 1: Buggy Fibonacci
// This fibonacci function returns wrong results. Find and fix the bug.
function buggyFib(n: number): number {
  if (n === 0) return 1; // BUG: wrong base case
  if (n === 1) return 1;
  return buggyFib(n - 1) + buggyFib(n - 2);
}

// console.log("Fix 1:", [0,1,2,3,4,5,6].map(buggyFib));
// Expected: [0, 1, 1, 2, 3, 5, 8]
// Actual:   [1, 1, 2, 3, 5, 8, 13]  — off by one!

// FIX 2: Buggy Flatten
// This recursive flatten doesn't work correctly for deeply nested arrays.
function buggyFlatten(arr: unknown[]): unknown[] {
  const result: unknown[] = [];
  for (const item of arr) {
    if (Array.isArray(item)) {
      result.push(buggyFlatten(item)); // BUG: push vs spread
    } else {
      result.push(item);
    }
  }
  return result;
}

// console.log("Fix 2:", buggyFlatten([1, [2, [3, 4], 5], 6]));
// Expected: [1, 2, 3, 4, 5, 6]
// Actual:   [1, [2, 3, 4, 5], 6]  — still nested!

// FIX 3: Buggy Power Function
// This power function has an infinite recursion bug for certain inputs.
function buggyPower(base: number, exp: number): number {
  if (exp === 0) return 1;
  if (exp % 2 === 0) {
    return buggyPower(base, exp / 2) * buggyPower(base, exp / 2); // BUG: not reducing efficiently but also...
  }
  return base * buggyPower(base, exp); // BUG: doesn't reduce exp!
}

// console.log("Fix 3:", buggyPower(2, 10));
// Expected: 1024
// Actual: Maximum call stack exceeded (for odd exp paths)

// ---------------------------------------------------------------------------
// IMPLEMENT EXERCISES (7)
// ---------------------------------------------------------------------------

// IMPLEMENT 1: Factorial (recursive)
// Time: O(n) | Space: O(n) call stack
function factorial(n: number): number {
  // TODO
  return 0;
}

// console.log("Impl 1a:", factorial(0));   // 1
// console.log("Impl 1b:", factorial(1));   // 1
// console.log("Impl 1c:", factorial(5));   // 120
// console.log("Impl 1d:", factorial(10));  // 3628800

// IMPLEMENT 2: Fibonacci with Memoization
// Return the nth fibonacci number. Use memoization to achieve O(n) time.
// fib(0)=0, fib(1)=1, fib(n) = fib(n-1) + fib(n-2)
// Time: O(n) | Space: O(n)
function fibMemo(n: number, memo: Map<number, number> = new Map()): number {
  // TODO
  return 0;
}

// console.log("Impl 2a:", fibMemo(0));    // 0
// console.log("Impl 2b:", fibMemo(1));    // 1
// console.log("Impl 2c:", fibMemo(10));   // 55
// console.log("Impl 2d:", fibMemo(40));   // 102334155

// IMPLEMENT 3: Power Function (fast exponentiation)
// Compute base^exp using O(log n) multiplications.
// Handle exp = 0 and negative exponents.
// Time: O(log n) | Space: O(log n) call stack
function power(base: number, exp: number): number {
  // TODO: Use the pattern: x^n = (x^(n/2))^2 for even n
  return 0;
}

// console.log("Impl 3a:", power(2, 10));   // 1024
// console.log("Impl 3b:", power(3, 0));    // 1
// console.log("Impl 3c:", power(2, -3));   // 0.125
// console.log("Impl 3d:", power(5, 3));    // 125

// IMPLEMENT 4: Flatten Nested Array
// Recursively flatten an arbitrarily nested array.
// Time: O(n) where n = total elements | Space: O(d) where d = max depth
function flatten(arr: unknown[]): unknown[] {
  // TODO
  return [];
}

// console.log("Impl 4a:", flatten([1, [2, [3, [4]], 5]]));          // [1, 2, 3, 4, 5]
// console.log("Impl 4b:", flatten([[1, 2], [3, [4, [5, [6]]]]]));  // [1, 2, 3, 4, 5, 6]
// console.log("Impl 4c:", flatten([]));                              // []

// IMPLEMENT 5: Deep Clone
// Recursively deep clone an object/array. Handle objects, arrays, and primitives.
// No need to handle Date, RegExp, Map, Set, functions, circular references.
// Time: O(n) | Space: O(n)
type Cloneable = string | number | boolean | null | undefined | CloneableArray | CloneableObject;
interface CloneableArray extends Array<Cloneable> {}
interface CloneableObject { [key: string]: Cloneable }

function deepClone(value: Cloneable): Cloneable {
  // TODO
  return value;
}

// const original = { a: 1, b: { c: [1, 2, { d: 3 }] } };
// const cloned = deepClone(original) as CloneableObject;
// console.log("Impl 5a:", JSON.stringify(cloned));
// console.log("Impl 5b: Not same ref:", cloned !== original);
// console.log("Impl 5c: Deep not same ref:", (cloned as any).b !== (original as any).b);

// IMPLEMENT 6: Generate All Subsets
// Given an array of unique numbers, return all possible subsets (power set).
// Time: O(2^n * n) | Space: O(2^n * n)
function subsets(nums: number[]): number[][] {
  // TODO: Use backtracking
  return [];
}

// console.log("Impl 6a:", subsets([1, 2, 3]));
// Expected: [[], [1], [1,2], [1,2,3], [1,3], [2], [2,3], [3]]
// (order may vary, but all 8 subsets should be present)

// IMPLEMENT 7: Tower of Hanoi
// Move n disks from source to target using auxiliary peg.
// Return array of moves as [from, to] tuples.
// Rules: move one disk at a time, never place larger on smaller.
// Time: O(2^n) | Space: O(n) call stack
function towerOfHanoi(
  n: number,
  source: string,
  target: string,
  auxiliary: string
): Array<[string, string]> {
  // TODO
  return [];
}

// console.log("Impl 7a:", towerOfHanoi(2, "A", "C", "B"));
// Expected: [["A","B"], ["A","C"], ["B","C"]]
// console.log("Impl 7b:", towerOfHanoi(3, "A", "C", "B"));
// Expected: 7 moves

// ---------------------------------------------------------------------------
// RUNNER (uncomment to test all)
// ---------------------------------------------------------------------------
// function runAll(): void {
//   console.log("=== PREDICT ===");
//   predictFactorial();
//   predictFibCalls();
//
//   console.log("\n=== FIX ===");
//   console.log("Fix 1:", [0,1,2,3,4,5,6].map(buggyFib));
//   console.log("Fix 2:", buggyFlatten([1, [2, [3, 4], 5], 6]));
//   console.log("Fix 3:", buggyPower(2, 10));
//
//   console.log("\n=== IMPLEMENT ===");
//   console.log("Impl 1:", factorial(5));
//   console.log("Impl 2:", fibMemo(40));
//   console.log("Impl 3:", power(2, 10));
//   console.log("Impl 4:", flatten([1, [2, [3, [4]], 5]]));
//   console.log("Impl 5:", deepClone({ a: 1, b: { c: [1, 2] } }));
//   console.log("Impl 6:", subsets([1, 2, 3]));
//   console.log("Impl 7:", towerOfHanoi(3, "A", "C", "B"));
// }
// runAll();

export {
  buggyFib,
  buggyFlatten,
  buggyPower,
  factorial,
  fibMemo,
  power,
  flatten,
  deepClone,
  subsets,
  towerOfHanoi,
};
export type { Cloneable, CloneableArray, CloneableObject };
